In [8]:
import pandas as pd

animeWatchedPerUser = pd.read_csv('cleaned/animelists_cleaned.csv')

In [9]:
animeWatchedPerUser.head()

,username,anime_id,my_watched_episodes,my_start_date,my_finish_date,my_score,my_status,my_rewatching,my_rewatching_ep,my_last_updated,my_tags
0,karthiga,21,586,0000-00-00,0000-00-00,9,1,NaN,0,2013-03-03 10:52:53,NaN
1,karthiga,59,26,0000-00-00,0000-00-00,7,2,NaN,0,2013-03-10 13:54:51,NaN
2,karthiga,74,26,0000-00-00,0000-00-00,7,2,NaN,0,2013-04-27 16:43:35,NaN
3,karthiga,120,26,0000-00-00,0000-00-00,7,2,NaN,0,2013-03-03 10:53:57,NaN
4,karthiga,178,26,0000-00-00,0000-00-00,7,2,0.0,0,2013-03-27 15:59:13,NaN

In [10]:
animeWatchedPerUser.describe()

,anime_id,my_watched_episodes,my_score,my_status,my_rewatching,my_rewatching_ep
count,3.128403e+07,3.128403e+07,3.128403e+07,3.128403e+07,2.440578e+07,3.128403e+07
mean,1.170326e+04,1.289615e+01,4.652315e+00,3.008111e+00,7.903045e-04,1.832994e-01
std,1.134844e+04,3.733380e+01,3.931615e+00,1.730421e+00,2.810124e-02,1.009172e+03
min,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,1.601000e+03,0.000000e+00,0.000000e+00,2.000000e+00,0.000000e+00,0.000000e+00
50%,8.086000e+03,4.000000e+00,6.000000e+00,2.000000e+00,0.000000e+00,0.000000e+00
75%,1.977500e+04,1.300000e+01,8.000000e+00,4.000000e+00,0.000000e+00,0.000000e+00
max,3.789600e+04,9.999000e+03,1.000000e+01,5.500000e+01,1.000000e+00,5.644513e+06

In [11]:
animeWatchedPerUser.dtypes

username                object
anime_id                 int64
my_watched_episodes      int64
my_start_date           object
my_finish_date          object
my_score                 int64
my_status                int64
my_rewatching          float64
my_rewatching_ep         int64
my_last_updated         object
my_tags                 object
dtype: object

In [12]:
def mark_completion(row):
    if row['my_start_date'] != '0000-00-00' and row['my_finish_date'] != '0000-00-00':
        return 'complete'
    elif row['my_finish_date'] == '0000-00-00' and row['my_start_date'] != '0000-00-00':
        return 'incomplete'
    else:
        return 'null'

animeWatchedPerUser['completion_status'] = animeWatchedPerUser.apply(mark_completion, axis=1)

In [13]:
def changeStatus(row):
    if row['my_status'] == 1:
        return 'watching'
    elif row['my_status'] == 2:
        return 'completed'
    elif row['my_status'] == 3:
        return 'on hold'
    elif row['my_status'] == 4:
        return 'dropped'
    elif row['my_status'] == 6:
        return 'plan to watch'

animeWatchedPerUser['my_status'] = animeWatchedPerUser.apply(changeStatus, axis=1)

In [14]:
filtered_df = animeWatchedPerUser[animeWatchedPerUser['completion_status'].isin(['complete', 'incomplete'])]
print(filtered_df)

               username  anime_id  my_watched_episodes my_start_date  \
72            Damonashu        68                   23    2008-08-07
73            Damonashu       107                    3    2008-09-30
98            Damonashu       356                    2    2009-10-15
105           Damonashu       486                    1    2008-09-30
109           Damonashu       861                   24    2009-03-02
...                 ...       ...                  ...           ...
31284018    Hentai-Time     17012                    1    2013-06-21
31284019    Hentai-Time     17543                    1    2013-06-21
31284020        puppals      5231                  103    2010-06-18
31284024  Yokonightcore      9539                   37    2013-04-21
31284025  Yokonightcore     15611                   48    2014-00-00

         my_finish_date  my_score  my_status  my_rewatching  my_rewatching_ep  \
72           2009-03-09         5  completed            0.0                 0
73           0000-00-00         0    dropped            NaN                 0
98           0000-00-00         0   watching            0.0                 0
105          0000-00-00         0    on hold            NaN                 0
109          2010-01-30         0  completed            0.0                 0
...                 ...       ...        ...            ...               ...
31284018     0000-00-00         0   watching            0.0                 0
31284019     0000-00-00         0   watching            0.0                 0
31284020     0000-00-00        10   watching            NaN                 0
31284024     0000-00-00         9   watching            NaN                 0
31284025     0000-00-00         9   watching            NaN                 0

              my_last_updated my_tags completion_status
72        2009-03-09 22:44:45     NaN          complete
73        2008-10-01 03:01:38     NaN        incomplete
98        2009-10-20 09:59:43     NaN        incomplete
105       2008-10-01 03:01:23     NaN        incomplete
109       2010-01-30 10:15:16     NaN          complete
...                       ...     ...               ...
31284018  2013-06-21 17:05:19     NaN        incomplete
31284019  2013-06-21 16:52:07     NaN        incomplete
31284020  2010-10-18 07:17:14     NaN        incomplete
31284024  2015-09-07 17:31:15     NaN        incomplete
31284025  2015-09-07 17:33:03     NaN        incomplete

[4863104 rows x 12 columns]